## Numpy Array Operation

In [1]:
import numpy as np

In [3]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Basic Slicing", arr[2:7])
print("With Step", arr[1:8:2])
print("Negative indexing", arr[-3])

Basic Slicing [3 4 5 6 7]
With Step [2 4 6 8]
Negative indexing 8


In [5]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print("Specific element", arr_2d[1, 2]) # with lists in python you must use two separate brackets (arr_2d[1][2]).
#arr_2d[1, 2] will give an error, because lists don’t understand tuple indexing.
print("Entire row: ", arr_2d[1])
print("Entire Col: ", arr_2d[:, 1]) # ERROR in Python lists [: => every row]

# col = [row[1] for row in arr_2d] => This is how u print col in python.
# print(col)

Specific element 6
Entire row:  [4 5 6]
Entire Col:  [2 5 8]


## Sorting

In [ ]:
unsorted = np.array([3, 1, 4, 1, 5, 9, 2, 6])
print("Sorted Array", np.sort(unsorted))

arr_2d_unsorted = np.array([[3, 1], [1, 2], [2, 3]])
print("Sorted 2D array by column", np.sort(arr_2d_unsorted, axis=0)) # axis = 0 => col wise sorting or 1 => row wise sorting

Sorted Array [1 1 2 3 4 5 6 9]
Sorted 2D array by column [[1 1]
 [2 2]
 [3 3]]


## Filtering

In [ ]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
even_number = numbers[numbers % 2 == 0] # filter numbers for even values.
print("Even numbers", even_number)

# What's happening here:

# numbers % 2  => It is a mask
# == 0 → creates a boolean mask (True for even, False for odd).
# numbers[...] → NumPy uses that mask to pick only the elements where the condition is True.
# ✅ Final result → all even numbers from the array.

Even numbers [ 2  4  6  8 10]


## Filter with mask

In [ ]:
mask = numbers > 5
print("Numbers greater than 5 ", numbers[mask])

# mask = [False False False False False  True  True  True  True  True]

# numbers[mask] -> Uses the boolean mask to filter elements from numbers.
#Wherever mask is True, it picks the element.

Numbers greater than 5  [ 6  7  8  9 10]


## Fancy indexing VS np.where()

In [ ]:
indices = [0, 2, 4]
print(numbers[indices]) # [1 3 5]

where_result = np.where(numbers > 5) # np.where returns the indices where the condition is True.
print(where_result)# [5, 6, 7, 8, 9]
print("NP where", numbers[where_result]) # At indices [5,6,7,8,9] → values [6,7,8,9,10].

[1 3 5]
(array([5, 6, 7, 8, 9]),)
NP where [ 6  7  8  9 10]


1. Boolean Masking

Syntax:
numbers[numbers > 5]


✅ Use it when:
1. You want the actual values that satisfy a condition.
2. You don’t care about the indices.
3. Code should be short and readable.

👉 Example:

numbers = np.arange(1, 11)
print(numbers[numbers % 2 == 0])  
 [ 2  4  6  8 10]

🔹 2. np.where

Syntax:
np.where(condition)


✅ Use it when:
1. You need the indices of elements that satisfy a condition.
2. Or when using the 3-argument form (like inline if-else).

👉 Example 1 (indices):

idx = np.where(numbers > 5)
print(idx)               # (array([5, 6, 7, 8, 9]),)
print(numbers[idx])      # [ 6  7  8  9 10]


👉 Example 2 (if-else replacement):

result = np.where(numbers % 2 == 0, "even", "odd")
print(result)
 ['odd' 'even' 'odd' 'even' ...]

In [ ]:
condition_array = np.where(numbers > 5, numbers*2,  "false") # creating an array that fullfils some conditions.
print(condition_array)

# if numbers > 5 is true then do numbers*2 else return false. 
# ['false' 'false' 'false' 'false' 'false' '12' '14' '16' '18' '20']

# With masking and np.where, a new array is created.
#The original (numbers) does not change unless you explicitly assign back.

['false' 'false' 'false' 'false' 'false' '12' '14' '16' '18' '20']


## Adding and Removing Data

In [14]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

combined = arr1 + arr2 
print(combined) # [5 7 9]

combined2 = np.concatenate((arr1, arr2))
print(combined2)


[5 7 9]
[1 2 3 4 5 6]


## Array Compatibility

In [16]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6, 7])
c = np.array([7, 8, 9])

print("Compatibility shapes", a.shape == b.shape)
print("Compatibility shapes", a.shape == c.shape)

Compatibility shapes False
Compatibility shapes True


## How to add a new row and col in array?

In [21]:
original = np.array([[1, 2], [3, 4]])
new_row = np.array([[5, 6]])

with_new_row = np.vstack((original, new_row)) # vertical stack -> adds a new row
print(original)
print(with_new_row)

new_col = np.array([[7], [8]])
with_new_col = np.hstack((original, new_col)) # horizontal stack -> adds a new col
print(" With new column \n", with_new_col)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
 With new column 
 [[1 2 7]
 [3 4 8]]


## How to delete?

Syntax:

np.delete(arr, obj, axis=None)

1. arr → input array 
2. obj → index(es) of elements/subarrays to remove 
3. axis → 
        1. None (default) → flatten the array before deletion , 0 → delete rows , 1 → delete columns

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
deleted = np.delete(arr, 2) # delete element at index 2 and returns rest of the array.
print("Array after deletion: ", deleted)

#2. Delete multiple elements
arr = np.array([1, 2, 3, 4, 5])
new_arr = np.delete(arr, [1, 3])  # delete indices 1 and 3
print(new_arr)
# [1 3 5]

# 3. Delete row from 2D array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

new_arr = np.delete(arr_2d, 1, axis=0)  # delete row at index 1
print(new_arr)
# [[1 2 3]
#  [7 8 9]]

# 4. Delete column from 2D array
new_arr = np.delete(arr_2d, 0, axis=1)  # delete column at index 0
print(new_arr)
# [[2 3]
#  [5 6]
#  [8 9]]


# Important Notes
# np.delete does not modify the original array. It creates and returns a new array.
# If you want in-place deletion, you’d need to reassign:

# arr = np.delete(arr, 2)

Array after deletion:  [1 2 4 5]
[1 3 5]
