Learn about numpy -> Shift Enter -> new cell

In [2]:
import numpy as np

Creating array from list

In [3]:
arr_1d = np.array([1 , 2 , 3 , 4 , 5]) # it takes only one argument -> list
print(arr_1d)

# numpy array generally takes same type of values.
arr_2d = np.array([[1 , 2 , 3 , 4] , [4 , 5 , 6 , 7]])
print(arr_2d)

[1 2 3 4 5]
[[1 2 3 4]
 [4 5 6 7]]


List V/s Numpy Array

In [4]:
py_List = [1 , 2 , 3]
print(py_List*2) # [1, 2, 3, 1, 2, 3]

np_array = np.array([1 , 2 , 3]) 
print(np_array*2) # element wise multiplication -> [2 , 4 , 6]



[1, 2, 3, 1, 2, 3]
[2 4 6]


Python List Operation:

1. Records the start time.

2. Creates a list (py_list) with 1,000,000 elements, each being i*2.
Example: [0, 2, 4, 6, 8, ..., 1999998]

3. Measures how long it takes and prints the duration.

4. This uses pure Python list comprehension, which is slower because it loops through each element in Python’s interpreter.

In [5]:
import time
start = time.time() #  starting time 
py_list = [i*2 for i in range(1000000)]
print("\n List operation time: ", time.time() - start) # here time.time() gives the finishing time
#  0.1728177070617675


 List operation time:  0.14409399032592773


NumPy Array Operation:
1. Records the start time again.

2. Creates a NumPy array with values from 0 to 999,999.

3. Multiplies the entire array by 2 in one vectorized operation.

4. Prints the time taken.

⚡ This is much faster because:
a. NumPy is implemented in C (low-level, optimized).
b. Uses vectorization (applies operations on whole arrays at once instead of looping element by element).

In [6]:
import time
start = time.time()
np_array = np.arange(1000000) * 2
print("\n Numpy operation time: ", time.time() - start) #   0.019168376922607422


 Numpy operation time:  0.006808757781982422


Creating Array From Scratch

In [7]:
zeros = np.zeros((3 , 4)) # this creates a array containing zeros of size -> 3 rows , 4 cols
print(zeros) 

ones = np.ones((2 , 3)) # this creates a array containing ones of size -> 2 rows , 3 cols
print(ones)

# Now , what if u want constants other than 0 , 1:
full = np.full((2 , 2) , 7) # (2 , 2) -> size  of matrix , 7 -> the const u want.
print(full) # [[7 7],  [7 7]]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[7 7]
 [7 7]]


Random Class:

In [ ]:
random = np.random.random((2,3)) # This creates a 2x3 matrix of random floating point no.s b/w 0 and 1
print(random)

random2 = np.random.random(5) # 1D array of length 5.
print(random2)

print(np.random.random()) # returns a floating no. b/w 0 and 1

sequence = np.arange(0, 10, 1) # Generates a sequence of evenly spaced numbers.
#Similar to Python’s built-in range(), but returns a NumPy array.
print(sequence) # [0 1 2 3 4 5 6 7 8 9]

# here , You specify:
# start (default = 0),
# stop (not included),
# step (default = 1).

[[0.67924099 0.77033698 0.88830257]
 [0.99419433 0.35780609 0.93265021]]
[0.64062914 0.75548866 0.36783384 0.31713968 0.29426954]
0.6409715429519782
[0 1 2 3 4 5 6 7 8 9]


Vector , Matrix and Tensor

In [ ]:
vector = np.array([1,2,3]) # Vector is a 1D Tensor
print(vector)

matrix = np.array([[1,2,3],[4 , 5 , 6]]) # Matrix is a 2D Tensor
print(vector)
print(matrix)

# 0D Tensor (scalar)
t0 = np.array(42)
print(t0)

# 3D Tensor
tensor = np.array([[[1,2] , [3,4]] ,
                    [[5,6] , [7,8]]]) # tensor in numpy consists of multidimenstional array.
print(tensor)

[1 2 3]
[1 2 3]
[[1 2 3]
 [4 5 6]]
0D: 42 Shape: ()
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Array Properties:

In [ ]:
arr = np.array([[1 , 2 , 3] , [4 , 5 , 6]])

# Prop1 -> Shape of array
print("Shape: ", arr.shape) # It gives no. of rows and cols. =>  Shape:  (2, 3)
# Prop2 -> Dimention of array
print("Dimention", arr.ndim)
print("Size: ", arr.size) # returns no. of elements in array.
print("DataType: " , arr.dtype) # returns type of array.


# Note:
# If you mix types while creating an array, NumPy will upcast 
# (convert everything to the most general type that can hold all values).
# If each element had a different type, NumPy couldn’t store them contiguously 
# in memory or use optimized C operations. So each element should be of same type.

Shape:  (2, 3)
Dimention 2
Size:  6
DataType:  int64


Array Operations

In [ ]:
arr = np.arange(12)
print("Original array ", arr)

reshaped = arr.reshape((3, 4)) # original arr gets converted into 3x4 matrix.
print("\n Reshaped array ", reshaped)

flattened = reshaped.flatten() # returns the 1D copy of  array
print("\n Flattened array ", flattened)

# ravel (returns view, instead of copy) => returns original arr.
raveled = reshaped.ravel()
print("\n raveled array ", raveled)

# Transpose
transpose = reshaped.T
print("\n Transposed array ", transpose)


# In NumPy, a view means that two arrays share the same data in memory.
# So if you change one, the other also changes.

# 🔹 reshape
# Changes the shape of the array without changing data.
# Number of elements must stay the same.
# Returns a view (no copy, unless needed).
# You can use -1 to auto-calculate a dimension.

# 🔹 flatten
# Converts array into 1D.
# Always returns a copy (independent of original).
# Original array is unaffected.

# 🔹 ravel
# Converts array into 1D.
# Returns a view if possible, otherwise a copy.
# If it’s a view, modifying it will also modify the original.